-- INSERINDO DADOS DA PRIMEIRA RODADA
-- JOGO 1 INT X BAH
INSERT INTO Serie_A (Ano_campeonato, Data_jogo, Horario, Rodada, Estadio, Arbitro, Publico, Time_mandante, Time_visitante, Tecnico_mandante, Tecnico_visitante, 
Colocacao_mandante, Colocacao_visitante, Idade_media_mandante, Idade_media_visitante, 
Gols_mandante,  Gols_visitante, Gols_HT_mandante, Gols_HT_visitante, 
Escanteios_mandante, Escanteio_visitante, Cartao_mandante, Cartao_visitante, 
Faltas_mandante, Faltas_visitante, 
Defesas_mandante, Defesas_visitante, 
Impedimentos_mandante, Impedimentos_visitante, 
Finalizacao_mandante, Finalizacao_visitante, SoT_mandante, SoT_visitante, 
Posse_de_bola_mandante, Posse_de_bola_visitante, 
Passes_mandante, Passes_visitante, Precisao_de_passes_mandante, Precisao_de_passes_visitante)
VALUES (2024, '13-04-2024', '18:30', 1, 'Beira-Rio', 'Rodrigo Jose Pereira de Lima', 19103, 'Internacional', 'Bahia', 'Eduardo Coudet', 'Rogério Ceni', 
NULL, NULL, 27, 29, 
2, 1, 0, 0, 
6, 3, 5, 3, 
21, 13, 
3, 7, 
3, 2, 
17, 9, 9, 4, 
53, 47, 
513, 467, 86, 83);

-- JOGO 2 CRI X JUV
INSERT INTO Serie_A (Ano_campeonato, Data_jogo, Horario, Rodada, Estadio, Arbitro, Publico, Time_mandante, Time_visitante, Tecnico_mandante, Tecnico_visitante, 
Colocacao_mandante, Colocacao_visitante, Idade_media_mandante, Idade_media_visitante, 
Gols_mandante,  Gols_visitante, Gols_HT_mandante, Gols_HT_visitante, 
Escanteios_mandante, Escanteio_visitante, Cartao_mandante, Cartao_visitante, 
Faltas_mandante, Faltas_visitante, 
Defesas_mandante, Defesas_visitante, 
Impedimentos_mandante, Impedimentos_visitante, 
Finalizacao_mandante, Finalizacao_visitante, SoT_mandante, SoT_visitante, 
Posse_de_bola_mandante, Posse_de_bola_visitante, 
Passes_mandante, Passes_visitante, Precisao_de_passes_mandante, Precisao_de_passes_visitante)
VALUES (2024, '13-04-2024', '18:30', 1, 'Heriberton Hulse', 'Bruno Pereira Vasconcelos', 12408, 'Criciúma', 'Juventude', 'Cláudio Tencati', 'Roger Machado',
NULL, NULL, 31, 30,
1, 1, 1, 0,
0, 4, 4, 6,
11, 15,
3, 2,
3, 4,
10, 15, 3, 4,
47, 53,
423, 464, 80, 81)

-- JOGO 3 FLU X BRA
INSERT INTO Serie_A (Ano_campeonato, Data_jogo, Horario, Rodada, Estadio, Arbitro, Publico, Time_mandante, Time_visitante, Tecnico_mandante, Tecnico_visitante, 
Colocacao_mandante, Colocacao_visitante, Idade_media_mandante, Idade_media_visitante, 
Gols_mandante,  Gols_visitante, Gols_HT_mandante, Gols_HT_visitante, 
Escanteios_mandante, Escanteio_visitante, Cartao_mandante, Cartao_visitante, 
Faltas_mandante, Faltas_visitante, 
Defesas_mandante, Defesas_visitante, 
Impedimentos_mandante, Impedimentos_visitante, 
Finalizacao_mandante, Finalizacao_visitante, SoT_mandante, SoT_visitante, 
Posse_de_bola_mandante, Posse_de_bola_visitante, 
Passes_mandante, Passes_visitante, Precisao_de_passes_mandante, Precisao_de_passes_visitante)
VALUES (2024, '13-04-2024', '21:00', 1, 'Maracanã', 'Meguielson Lima Barbosa', 17645, 'Fluminense', 'Bragantino', 'Fernando Diniz', 'Pedro Caixinha',
NULL, NULL, 31.4, 24.5,
2, 2, 1, 0,
13, 6, 3, 4,
8, 19,
6, 9,
0, 0,
26, 16, 11, 8,
69, 31,
520, 228, 87, 69)

--- JOGO 4 SÃO X FOR 
INSERT INTO Serie_A (Ano_campeonato, Data_jogo, Horario, Rodada, Estadio, Arbitro, Publico, Time_mandante, Time_visitante, Tecnico_mandante, Tecnico_visitante, 
Colocacao_mandante, Colocacao_visitante, Idade_media_mandante, Idade_media_visitante, 
Gols_mandante,  Gols_visitante, Gols_HT_mandante, Gols_HT_visitante, 
Escanteios_mandante, Escanteio_visitante, Cartao_mandante, Cartao_visitante, 
Faltas_mandante, Faltas_visitante, 
Defesas_mandante, Defesas_visitante, 
Impedimentos_mandante, Impedimentos_visitante, 
Finalizacao_mandante, Finalizacao_visitante, SoT_mandante, SoT_visitante, 
Posse_de_bola_mandante, Posse_de_bola_visitante, 
Passes_mandante, Passes_visitante, Precisao_de_passes_mandante, Precisao_de_passes_visitante)
VALUES (2024, '13-04-2024', '21:00', 1, 'MorumBIS', 'Alex Gomes Stefano', 35055, 'São Paulo', 'Fortaleza', 'Thiago Carpini', 'Juan Pablo Vojvoda',
NULL, NULL, 28.3, 31.2,
1, 2, 0, 0,
11, 4, 2, 3,
10, 14,
4, 7,
0, 0,
14, 6, 5 ,2,
72, 28,
691, 272, 88, 68)

-- JOGO 5 ATH X CUI
INSERT INTO Serie_A (Ano_campeonato, Data_jogo, Horario, Rodada, Estadio, Arbitro, Publico, Time_mandante, Time_visitante, Tecnico_mandante, Tecnico_visitante, 
Colocacao_mandante, Colocacao_visitante, Idade_media_mandante, Idade_media_visitante, 
Gols_mandante,  Gols_visitante, Gols_HT_mandante, Gols_HT_visitante, 
Escanteios_mandante, Escanteio_visitante, Cartao_mandante, Cartao_visitante, 
Faltas_mandante, Faltas_visitante, 
Defesas_mandante, Defesas_visitante, 
Impedimentos_mandante, Impedimentos_visitante, 
Finalizacao_mandante, Finalizacao_visitante, SoT_mandante, SoT_visitante, 
Posse_de_bola_mandante, Posse_de_bola_visitante, 
Passes_mandante, Passes_visitante, Precisao_de_passes_mandante, Precisao_de_passes_visitante)
VALUES (2024, '14-04-2024', '16:00', 1, 'Ligga Arena', 'Jonathan Benkenstein Pinheiro', 22169, 'Athletico', 'Cuiabá', 'Cuca', 'Luiz Fernando Lubel',
NULL, NULL, 29.2, 27.8,
4, 0, 3, 0,
7, 0, 0, 3,
16, 9,
0, 5,
2,1,
20, 1, 9, 0,
62, 38,
582, 367, 88, 84)

-- JOGO 6 VAS X GRE
INSERT INTO Serie_A (Ano_campeonato, Data_jogo, Horario, Rodada, Estadio, Arbitro, Publico, Time_mandante, Time_visitante, Tecnico_mandante, Tecnico_visitante, 
Colocacao_mandante, Colocacao_visitante, Idade_media_mandante, Idade_media_visitante, 
Gols_mandante,  Gols_visitante, Gols_HT_mandante, Gols_HT_visitante, 
Escanteios_mandante, Escanteio_visitante, Cartao_mandante, Cartao_visitante, 
Faltas_mandante, Faltas_visitante, 
Defesas_mandante, Defesas_visitante, 
Impedimentos_mandante, Impedimentos_visitante, 
Finalizacao_mandante, Finalizacao_visitante, SoT_mandante, SoT_visitante, 
Posse_de_bola_mandante, Posse_de_bola_visitante, 
Passes_mandante, Passes_visitante, Precisao_de_passes_mandante, Precisao_de_passes_visitante)
VALUES (2024, '14-04-2024', '16:00', 1, 'São Januário', 'Flavio Rodrigues de Souza', 18055, 'Vasco', 'Grêmio', 'Ramón Díaz', 'Reanto Gaúcho',
NULL, NULL, 28.3, 28.9,
2, 1, 2, 1,
3, 5, 4, 1,
19, 10,
1, 1,
1, 1,
15, 9, 3, 2,
47, 53,
446, 504, 86, 87)

-- JOGO 7 COR X ATL
INSERT INTO Serie_A (Ano_campeonato, Data_jogo, Horario, Rodada, Estadio, Arbitro, Publico, Time_mandante, Time_visitante, Tecnico_mandante, Tecnico_visitante, 
Colocacao_mandante, Colocacao_visitante, Idade_media_mandante, Idade_media_visitante, 
Gols_mandante,  Gols_visitante, Gols_HT_mandante, Gols_HT_visitante, 
Escanteios_mandante, Escanteio_visitante, Cartao_mandante, Cartao_visitante, 
Faltas_mandante, Faltas_visitante, 
Defesas_mandante, Defesas_visitante, 
Impedimentos_mandante, Impedimentos_visitante, 
Finalizacao_mandante, Finalizacao_visitante, SoT_mandante, SoT_visitante, 
Posse_de_bola_mandante, Posse_de_bola_visitante, 
Passes_mandante, Passes_visitante, Precisao_de_passes_mandante, Precisao_de_passes_visitante)
VALUES (2024, '14-04-2024', '16:00', 1, 'Neo Química Arena', 'Yuri Elino Ferreira da Cruz', 44597, 'Corinthians', 'Atlético MG', 'António Oliveira', 'Gabriel Milito',
NULL, NULL, 28.0, 29.7,
0, 0, 0, 0,
3, 3, 8, 7,
16, 14,
3, 2,
0, 2,
14, 8, 2, 3,
48, 52,
347, 400, 80, 80)

-- JOGO 8 AGO X FLA
INSERT INTO Serie_A (Ano_campeonato, Data_jogo, Horario, Rodada, Estadio, Arbitro, Publico, Time_mandante, Time_visitante, Tecnico_mandante, Tecnico_visitante, 
Colocacao_mandante, Colocacao_visitante, Idade_media_mandante, Idade_media_visitante, 
Gols_mandante,  Gols_visitante, Gols_HT_mandante, Gols_HT_visitante, 
Escanteios_mandante, Escanteio_visitante, Cartao_mandante, Cartao_visitante, 
Faltas_mandante, Faltas_visitante, 
Defesas_mandante, Defesas_visitante, 
Impedimentos_mandante, Impedimentos_visitante, 
Finalizacao_mandante, Finalizacao_visitante, SoT_mandante, SoT_visitante, 
Posse_de_bola_mandante, Posse_de_bola_visitante, 
Passes_mandante, Passes_visitante, Precisao_de_passes_mandante, Precisao_de_passes_visitante)
VALUES (2024, '14-04-2024', '16:00', 1, 'Antônio Accioly', 'Andre Luiz Skettino Policarpo Bento', 35195, 'Atlético GO', 'Flamengo', 'Jair Ventura', 'Tite',
NULL, NULL, 26.2, 28.0,
1, 2, 0, 1,
4, 4, 5, 3,
12, 12,
0, 3,
2, 1,
11, 15, 4, 2,
32, 68,
208, 471, 72, 86)

-- JOGO 9 CRU X BOT
INSERT INTO Serie_A (Ano_campeonato, Data_jogo, Horario, Rodada, Estadio, Arbitro, Publico, Time_mandante, Time_visitante, Tecnico_mandante, Tecnico_visitante, 
Colocacao_mandante, Colocacao_visitante, Idade_media_mandante, Idade_media_visitante, 
Gols_mandante,  Gols_visitante, Gols_HT_mandante, Gols_HT_visitante, 
Escanteios_mandante, Escanteio_visitante, Cartao_mandante, Cartao_visitante, 
Faltas_mandante, Faltas_visitante, 
Defesas_mandante, Defesas_visitante, 
Impedimentos_mandante, Impedimentos_visitante, 
Finalizacao_mandante, Finalizacao_visitante, SoT_mandante, SoT_visitante, 
Posse_de_bola_mandante, Posse_de_bola_visitante, 
Passes_mandante, Passes_visitante, Precisao_de_passes_mandante, Precisao_de_passes_visitante)
VALUES (2024, '14-04-2024', '17:00', 1, 'Mineirão', 'Matheus Delgado Candancan', 20701, 'Cruzeiro', 'Botafogo', 'Fernando Seabra', 'Artur Jorge',
NULL, NULL, 29.0, 29.0,
3, 2, 1, 1,
6, 3, 4, 4,
12, 11, 
1, 2,
2, 0,
15, 6, 5, 3,
56, 44,
399, 319, 84, 79)

-- JOGO 10 VIT X PAL
INSERT INTO Serie_A (Ano_campeonato, Data_jogo, Horario, Rodada, Estadio, Arbitro, Publico, Time_mandante, Time_visitante, Tecnico_mandante, Tecnico_visitante,
Colocacao_mandante, Colocacao_visitante, Idade_media_mandante, Idade_media_visitante, 
Gols_mandante,  Gols_visitante, Gols_HT_mandante, Gols_HT_visitante, 
Escanteios_mandante, Escanteio_visitante, Cartao_mandante, Cartao_visitante, 
Faltas_mandante, Faltas_visitante, 
Defesas_mandante, Defesas_visitante, 
Impedimentos_mandante, Impedimentos_visitante, 
Finalizacao_mandante, Finalizacao_visitante, SoT_mandante, SoT_visitante, 
Posse_de_bola_mandante, Posse_de_bola_visitante, 
Passes_mandante, Passes_visitante, Precisao_de_passes_mandante, Precisao_de_passes_visitante)
VALUES (2024, '14-04-2024', '18:30', 1, 'Manoel Barradas', 'Braulio da Silva Machado', 30793, 'Vitória', 'Palmeiras', 'Léo Condé', 'Abel Ferreira',
NULL, NULL, 27.8, 26.1,
0, 1, 0, 1,
3, 9, 3, 5,
12, 15,
3, 5,
2, 3,
13, 15, 5, 4,
56, 44,
403, 307, 84, 73)


